#!/usr/bin/env python3
"""
Assign each of the 32,501 free-text product strings in the contract file to one
of twenty-two production classes.

The strings are truncated catalogue descriptions -- median seventeen characters,
maximum twenty-four -- so they are keyword-classifiable rather than needing any
model. Two passes: multi-word phrases that no single token identifies ("FIRE
CONTROL", "LANDING CRAFT"), then a token match against ordered stem sets, first
class wins. Ordering matters: "AIRPLANE ENGINES" must reach `aircraft` before
`machinetool` claims ENGINE, and "SHIP PROPULSION MACHRY" must reach `ships`.

Plurals are handled by generating candidate stems per token rather than by
stemming, because a stemmer that strips ES turns CARTRIDGES into CARTRIDG and
silently drops a billion dollars of ammunition into the residual.

Coverage: 95.2 percent of contract dollars and 85.2 percent of records. The
residual is a diffuse tail of 8,724 strings whose largest single entry is
$62 million against a $181 billion total.
"""
import re

TOK = re.compile(r'[A-Z]+')

def tokens(s):
    """Every token plus its plausible singular forms."""
    out = set()
    for t in TOK.findall(s):
        out.add(t)
        if len(t) > 3 and t.endswith('S'):   out.add(t[:-1])
        if len(t) > 4 and t.endswith('ES'):  out.add(t[:-2])
        if len(t) > 5 and t.endswith('IES'): out.add(t[:-3] + 'Y')
    return out

PHRASE = [
    ('firearms', 'FIRE CONTROL'), ('firearms', 'GUN DIRECTOR'),
    ('unclassifiable', 'CLASSIFIED'),
    ('aircraft', 'AIR FRAME'), ('aircraft', 'LANDING GEAR'),
    ('aircraft', 'BARRAGE BALLOON'),
    ('ships', 'LANDING CRAFT'), ('ships', 'LANDING SHIP'),
    ('ships', 'LANDING VEHICLE'),
    ('tanks', 'SCOUT CAR'), ('tanks', 'HALF TRACK'),
    ('machinetool', 'POWER UNIT'), ('machinetool', 'GENERATOR SET'),
    ('electrical', 'SPARK PLUG'), ('electrical', 'VACUUM TUBE'),
    ('electrical', 'SOUND SIG'),
]

RULES = [
 ('aircraft',    'AIRPLANE AIRPLNE AIRPL AIRCRAFT AIRCFT AIRCRFT PLANE BOMBER FIGHTER PURSUIT GLIDER '
                 'SEAPLANE AERO AERONAUT NACELLE FUSELAGE EMPENNAGE AILERON PROPELLER PROP AIRFRAME '
                 'AIRSCREW HELICOPTER BOMBSIGHT TURBOSUPERCHARGER SUPERCHARGER PONTOON WING COWLING '
                 'PARACHUTE BLIMP AIRSHIP'),
 ('ships',       'SHIP SHIPBUILD DESTROYER TANKER VESSEL FREIGHTER CORVETTE FRIGATE CRUISER BATTLESHIP '
                 'SUBMARINE SUBCHASER MINESWEEPER TUG BARGE LIGHTER DRYDOCK HULL LST LCI LCT LCVP LSM '
                 'LSD LCM APA AKA TROOPSHIP TRANSPORT SEATRAIN DERRICK SCOW DREDGE BOAT CRAFT SWEEPER '
                 'DOCK RAFT PRESERVER BUOY ANCHOR MOORING LVT AMPHIBIAN MARINE NAVAL'),
 ('railroad',    'LOCOMOTIVE RAILROAD RAILWAY RAILCAR CABOOSE GONDOLA RAIL TRACKAGE'),
 ('tanks',       'TANK COMBAT ARMORED HALFTRACK'),
 ('motorveh',    'TRUCK JEEP AUTOMOBILE AUTOMOTIVE TRAILER SEMITRAILER CHASSIS AMBULANCE MOTORCYCLE BUS '
                 'CARRIER TRACTOR BULLDOZER CRANE GRADER SCRAPER SHOVEL WAGON CART BICYCLE VEHICLE BODY '
                 'BRAKE AXLE WHEEL'),
 ('ammunition',  'CARTRIDGE SHELL AMMUNITION AMMO FUZE FUSE BOMB PROJECTILE GRENADE TORPEDO ROCKET '
                 'PRIMER DETONATOR BOOSTER BULLET CLIP SHOT BALL BANDOLEER MAGAZINE PYROTECHNIC FLARE '
                 'SIGNAL WARHEAD'),
 ('explosives',  'TNT EXPLOSIVE POWDER SMOKELESS NITROCELLULOSE NITRATE NITRO DYNAMITE RDX TETRYL '
                 'PROPELLANT TRINITROTOLUOL TRINITROTOLUENE AMATOL PICRIC ALKYLATE'),
 ('firearms',    'RIFLE CARBINE GUN MACHINEGUN SUBMACHINE PISTOL REVOLVER CANNON HOWITZER MORTAR '
                 'ARTILLERY MOUNT CARRIAGE BARREL BAYONET RECOIL TURRET ORDNANCE DIRECTOR RANGEFINDER '
                 'BREECH BOMBRACK LAUNCHER'),
 ('petroleum',   'GASOLINE PETROLEUM KEROSENE LUBRICANT LUBRICATING LUBE GREASE ASPHALT NAPHTHA TOLUOL '
                 'TOLUENE CRUDE BENZOL PARAFFIN WAX OIL'),
 ('chemicals',   'CHEMICAL ACID ALCOHOL AMMONIA CAUSTIC SODA CHLORINE SULFUR SULPHUR SOLVENT DYE PAINT '
                 'LACQUER VARNISH GLYCERIN GLYCERINE PHENOL PLASTIC RESIN INSECTICIDE PHARMACEUTICAL '
                 'PENICILLIN SERUM PLASMA MEDICAL SURGICAL DRUG BANDAGE GAUZE SULFA OXYGEN HELIUM '
                 'ACETATE ACETONE FORMALDEHYDE'),
 ('rubber',      'RUBBER TIRE TYRE BUNA LATEX HOSE GASKET'),
 ('leather',     'SHOE BOOT LEATHER HARNESS SADDLE'),
 ('textiles',    'CLOTH DUCK COTTON WOOL WOOLEN WORSTED RAYON SILK LINEN BURLAP CANVAS WEBBING TENT '
                 'TENTAGE TARPAULIN BLANKET UNIFORM JACKET TROUSER SHIRT COAT OVERCOAT RAINCOAT SOCK '
                 'UNDERWEAR GLOVE MITTEN YARN THREAD TWINE ROPE CORDAGE NETTING NET BAG SLEEPING '
                 'CLOTHING GARMENT APPAREL TOWEL CAP HAT HELMET LINER LEGGING POUCH HAVERSACK KNAPSACK '
                 'DUFFEL COMFORTER MATTRESS PILLOW FELT DRAWER UNDERSHIRT PONCHO SUIT TIE HANDKERCHIEF'),
 ('lumber',      'LUMBER PLYWOOD TIMBER WOOD WOODEN BOX CRATE PALLET VENEER PULP PAPER CARTON FURNITURE '
                 'CHEST BARREL KEG DUNNAGE'),
 ('ironsteel',   'STEEL IRON ARMOR PLATE STRIP FORGING CASTING PIPE TUBING STRUCTURAL BILLET INGOT SCRAP '
                 'FERRO ALLOY WELDING RIVET BOLT NUT SCREW NAIL SPIKE CHAIN FASTENER STAMPING '
                 'SHEETMETAL GALVANIZED'),
 ('nonferrous',  'COPPER BRASS BRONZE ALUMINUM ALUMINIUM ZINC LEAD MAGNESIUM TIN NICKEL CHROMIUM '
                 'MANGANESE TUNGSTEN SOLDER BABBITT SILVER PLATINUM ANTIMONY'),
 ('stoneclay',   'CEMENT CONCRETE BRICK STONE CLAY GLASS ASBESTOS CERAMIC REFRACTORY GRAVEL SAND LIME '
                 'GYPSUM ABRASIVE MICA GRAPHITE INSULATION ROOFING'),
 ('instruments', 'INSTRUMENT GAUGE GAGE OPTICAL OPTIC BINOCULAR TELESCOPE PERISCOPE COMPASS SIGHT '
                 'CHRONOMETER METER INDICATOR ALTIMETER THERMOMETER LENS LENSE PRISM CAMERA '
                 'PHOTOGRAPHIC XRAY WATCH CLOCK TACHOMETER INSTR PRECISION COMPUTER GYRO GYROSCOPE '
                 'AUTOPILOT PILOT NAVIGATION SEXTANT'),
 ('electrical',  'RADIO RADAR COMMUNICATION COMMUNICATN COMMUNICATNS ELECTRIC ELECTRICAL ELECTRONIC '
                 'WIRE CABLE GENERATOR MOTOR BATTERY TELEPHONE TELEGRAPH TRANSFORMER SWITCHBOARD '
                 'SWITCHGEAR TUBE ANTENNA SEARCHLIGHT LAMP LIGHTING CONDUIT INSULATOR RECTIFIER '
                 'CONDENSER RESISTOR SONAR LORAN TRANSMITTER RECEIVER DYNAMOTOR SOLENOID RELAY CRYSTAL '
                 'HEADSET MICROPHONE LOUDSPEAKER AMPLIFIER'),
 ('machinetool', 'TOOL LATHE DRILL MILLING GRINDER PRESS SHAPER BORING BROACH DIE JIG FIXTURE GEAR '
                 'BEARING PUMP COMPRESSOR VALVE TURBINE BOILER ENGINE MACHINERY MACHINE WINCH HOIST '
                 'CONVEYOR REFRIGERATION REFRIGERATOR BLOWER FAN CLUTCH TRANSMISSION SPRING PISTON '
                 'CYLINDER CRANKSHAFT CARBURETOR RADIATOR MAGNETO STARTER ENG POWER UNIT PLUG CUTTER '
                 'HARDWARE EXTINGUISHER INJECTOR APPARATUS EQUIPMENT'),
 ('food',        'FOOD RATION MEAT BEEF PORK FLOUR SUGAR CANNED BISCUIT COFFEE MILK BUTTER CHEESE EGG '
                 'VEGETABLE FRUIT CEREAL BREAD SOUP JUICE SUBSISTENCE POULTRY FISH POTATO BEAN RICE '
                 'SALT YEAST CHOCOLATE CANDY TOBACCO CIGARETTE DEHYDRATED'),
 ('construction','CONSTRUCTION BUILDING HOUSING BARRACK HANGAR WAREHOUSE PIPELINE ROAD AIRFIELD RUNWAY '
                 'DREDGING EXCAVATION ARCHITECT FACILITY PLANT DEPOT'),
 ('services',    'SERVICE TRAINING REPAIR OVERHAUL MAINTENANCE STORAGE TRANSPORTATION LAUNDRY RESEARCH '
                 'TESTING SALVAGE CONVERSION ALTERATION DEVELOPMENT STEVEDORING SERV SERVS ENGINEERING'),
]
SETS = [(k, set(v.split())) for k, v in RULES]

def classify(s):
    s = s.upper().strip()
    for k, ph in PHRASE:
        if ph in s: return k
    T = tokens(s)
    for k, S in SETS:
        if T & S: return k
    return 'unclassified'

def classify_series(products):
    """Vectorised over a pandas Series; caches on the distinct strings."""
    cache = {s: classify(s) for s in products.dropna().unique()}
    return products.map(cache)

CLASSES = [k for k, _ in RULES] + ['unclassifiable', 'unclassified']
